apiVersion: v2
name: kafka-kraft
description: Strimzi-based Kafka cluster in KRaft mode (requires Strimzi operator installed)
type: application
version: 0.1.0
appVersion: "4.0.0"
dependencies:
  - name: strimzi-kafka-operator
    version: "0.49.0"
    repository: "https://strimzi.io/charts/"
    condition: strimzi.enabled
