# This template creates a Kubernetes Secret
# to store the client ID and client secret for JupyterHub's OAuthenticator. 
# The values are base64 encoded and stored in a key called "values.yaml". 
# The secret is only created if both the client ID and client secret are provided in the Helm values.
{{- $clientId := .Values.jupyterhub.hub.config.GenericOAuthenticator.client_id | default "" }}
{{- $clientSecret := .Values.jupyterhub.hub.config.GenericOAuthenticator.client_secret | default "" }}
{{- if and $clientId $clientSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: jupyterhub-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  values.yaml: {{ printf "hub:\n  config:\n    GenericOAuthenticator:\n      client_id: %s\n      client_secret: %s\n" $clientId $clientSecret | b64enc }}
{{- end }}
